service: serverless-firebase-app

provider:
  name: aws
  runtime: nodejs6.10
  stage: v1
  region: us-east-1
  profile: prod
  memorySize: 1024
  timeout: 15
  environment:
    FIREBASE_PRIVATE_KEY: ${env:FIREBASE_PRIVATE_KEY}
    FIREBASE_CLIENT_EMAIL: ${env:FIREBASE_CLIENT_EMAIL}
    FIREBASE_PROJECT_ID: ${env:FIREBASE_PROJECT_ID}
    FIREBASE_DATABASE_URL: ${env:FIREBASE_DATABASE_URL}

functions:
  render:
    handler: handler.render
    events:
      - http:
          path: page
          method: get
